[package]
name = "mq-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
mod_exp = "1.0.1"
rand = "0.8.5"
